FROM debian
RUN apt-get update && apt-get -y upgrade && apt -y install nginx && apt-get clean && \
    cd /var/www/ && rm -rf ./* && \
    mkdir -p tama.com/img && \
    chmod -R 754 /var/www/tama.com/ && \
    useradd TAM && groupadd LYZH && usermod -aG LYZH TAM && \
    chown -R TAM:LYZH /var/www/tama.com/ && \
    sed -i 's/\/var\/www\/html/\/var\/www\/tama.com/g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user TAM/g' /etc/nginx/nginx.conf
ADD index.html /var/www/tama.com/
ADD img.jpg /var/www/tama.com/img/
CMD ["nginx", "-g", "daemon off;"]